1.1 Считайте число n. Создайте в переменной Z Numpy вектор из нулей длины n.

In [ ]:
import numpy as np

n = int(input("Введите количество чисел в массиве: "))
Z = np.zeros(n)

#print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

n = int(input("Введите количество чисел в массиве: "))
Z = np.full(n, 0.)

#print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

1.2. Посчитайте размер матрицы Z в байтах и выведите его на печать. Чтобы узнать
размер (в байтах) 1 элемента матрицы используйте
атрибут https://docs.scipy.org/doc/numpy1.15.1/reference/generated/numpy.ndarray.itemsize.html

In [49]:
import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

import numpy as np

class Matr:
    def __init__(self, dlin, Z = []):
        self.dlin = dlin
        self.Z = Z

        
    def bait1 (self):
        self.Z = np.random.random()
        self.dlin = Z.itemsize
        print(timeit.timeit('"-".join(str(n) for n in range(100))', number=10000))
        return self.dlin
        
    def bait2 (self):
        self.Z = np.array([1,2,3], dtype=np.float64)
        self.dlin = len(str(self.Z))
        print(timeit.timeit('"-".join(str(n) for n in range(100))', number=10000))
        return self.dlin 
    
    def bait3 (self):
        self.Z = np.zeros((10,10))
        self.dlin = Z.itemsize
        print(timeit.timeit('"-".join(str(n) for n in range(100))', number=10000))
        return self.dlin 
    
    
obj1 = Matr(0, 0)
print(obj1.bait1())
print(obj1.bait2())
print(obj1.bait3())

0.24836681199985833
8
0.2458149610001783
10
0.23940903100037758
8


1.3. Считайте 2 числа:

 n - размер Numpy вектора

 x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора
должны быть равны 0. Сохраните вектор в переменную Z.


In [7]:
import numpy as np

n = int(input("Введите количество чисел в массиве: "))
Z = np.zeros(n)
x = int(input("Введите координату элемента вектора который должен быть равен 1: "))
Z[x] = 1

print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

Введите количество чисел в массиве: 10
Введите координату элемента вектора который должен быть равен 1: 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


0.23625716600002988

In [11]:
import numpy as np

n = int(input("Введите количество чисел в массиве: "))
Z = np.full(n, 0.)
x = int(input("Введите координату элемента вектора который должен бытть равен 1: "))
Z[x] = 1
print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

Введите количество чисел в массиве: 100
Введите координату элемента вектора который должен бытть равен 1: 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


0.23874455199995737

1.4. Считайте 2 числа n, m. Создайте вектор Z состоящий из чисел от n до m с шагом 1.


In [13]:
import numpy as np

n = int(input("Введите первое число вектора: "))
m = int(input("Введите второе число вектора: "))
Z = np.arange(n, m)

print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)


Введите первое число вектора: 10
Введите второе число вектора: 50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


0.2432243409999728

1.5. Дан вектор Z. "Разверните" его.

In [ ]:
import numpy as np

n = int(input("Введите количество чисел в массиве: "))
Z = np.random.random(n)
#print(Z)
Z = Z[::-1]
#print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

[4 3 2 1]


In [15]:
import numpy as np

n = int(input("Введите количество чисел в массиве: "))
Z = np.arange(n)

for elem in reversed(Z):
    print(elem)
    
import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

Введите количество чисел в массиве: 10
9
8
7
6
5
4
3
2
1
0


0.24738146799995775

1.6. Считайте 3 числа:

 n - количество элементов матрицы

 m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).
Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется
пустых мест.

In [16]:
import numpy as np

n = int(input("Введите количество чисел в массиве: "))
m = int(input("Введите количество строк: "))
k = int(input("Введите количество столбцов: "))
Z = np.arange(n).reshape(m, k)


print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

Введите количество чисел в массиве: 6
Введите количество строк: 2
Введите количество столбцов: 3
[[0 1 2]
 [3 4 5]]


0.23956213999986176

In [17]:
import numpy as np

n = int(input("Введите количество элементов матрицы: "))
m = int(input("Введите количество строк: "))
k = int(input("Введите количество столбцов: "))
counter = 0
Z = np.full((m, k), n)
for row in range(m):
    for colum in range(k):
        Z[row][colum] = counter
        counter += 1

print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)


Введите количество элементов матрицы: 9
Введите количество строк: 3
Введите количество столбцов: 3
[[0 1 2]
 [3 4 5]
 [6 7 8]]


0.2552814869998201

1.7. Дан вектор Z. Запишите в переменную NonZerros индексы ненулевых элементов

In [18]:
import numpy as np

Z = np.array([0, 2, 4, 6])
def NZ():
    NonZerros = np.nonzero(Z)
    print(NonZerros)

K = np.array([1, 0, 2, 0, 3, 0, 4])
def NZ1():
    NonZerros1 = np.nonzero(K)
    print(NonZerros1)

Q = [1, 2, 0, 0, 4, 0]
def NZ2():
    NonZerros1 = np.nonzero(Q)
    print(NonZerros1)

NZ()
NZ1()
NZ2()

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

(array([1, 2, 3]),)
(array([0, 2, 4, 6]),)
(array([0, 1, 4]),)


0.26424201300005734

1.8. Считайте число n. Создайте единичную матрицу размера n, сохраните результат в
переменную Z.

In [21]:
import numpy as np

n = int(input("Введите количество единиц в массиве: "))
Z = np.eye(n)

print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

Введите количество единиц в массиве: 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


0.24171128200009662

In [22]:
import numpy as np

n = int(input("Введите количество чисел в массиве: "))
Z = np.identity(n)


print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

Введите количество чисел в массиве: 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


0.2555316989999028

1.9 Считайте 3 числа: n, m, l.. Зафиксируйте значение генератора случайных чисел Numpy
с помощью numpy.random.seed(42) . Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и
сохраните результат в переменную Z.

In [29]:
import numpy as np

n = int(input("Введите количество чисел в массиве: "))
m = int(input("Введите количество строк: "))
l = int(input("Введите количество столбцов: "))
np.random.seed(42)
Z = np.random.random(n)
Z = Z.reshape(m, l)

print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

Введите количество чисел в массиве: 4
Введите количество строк: 2
Введите количество столбцов: 2
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


0.2391204180000841

In [27]:
import numpy as np

n = int(input("Введите количество чисел в массиве: "))
m = int(input("Введите количество строк: "))
l = int(input("Введите количество столбцов: "))
np.random.seed(42)
X =  np.random.rand(m,l)
print(X)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

Введите количество чисел в массиве: 2
Введите количество строк: 2
Введите количество столбцов: 2
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


0.23495902500008015

1.10. Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с
помощью numpy.random.seed(42). Создайте матрицу n*m из случайных чисел (от 0 до 1).
5
Выведите на печать значение минимального и максимального чисел в получившейся
матрице (каждое с новой строки).

In [30]:
import numpy as np

n = int(input("Введите: "))
m = int(input("Введите: "))
np.random.seed(42)


Z = np.random.random((n, m))
Zmin, Zmax = Z.min(), Z.max()

print(Zmin) 
print(Zmax)


import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

Введите: 10
Введите: 10
0.005522117123602399
0.9868869366005173


0.24899841300020853

1.11. Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с
помощью numpy.random.seed(42).Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение среднего для всей матрицы.


In [32]:
import numpy as np

n = int(input("Введите: "))
m = int(input("Введите: "))
Z = np.random.random((n,m))
C = Z.mean()
print(C)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

Введите: 30
Введите: 30
0.509364010211792


0.24526792500000738

1.12. Переменные A и B содержат по numpy вектору. Найдите их скалярное произведение и
сохраните в переменную Z.

In [33]:
A = np.array([1.5,2.5,3.5])
B = np.array([4,5,6])
Z = np.dot(A,B)
print(Z)

39.5


In [35]:
A = np.array([1,3,5,7,9])
B = np.array([-2,4,-6,8,-10])
Z = np.dot(A,B)
print(Z)

-54


1.13. Даны 2 матрицы: A и B. Найдите произведение матриц и сохраните его в переменную Z.
Если найти произведение матриц невозможно, то запишите в Z строку:


In [46]:
n1 = int(input("Введите количество чисел в массиве 1: "))
m1 = int(input("Введите количество строк: "))
k1 = int(input("Введите количество столбцов: "))
A = np.arange(n1).reshape(m1, k1)

q2 = int(input("Введите первое число вектора в массиве 2: "))
w2 = int(input("Введите последнее число вектора: "))
m2 = int(input("Введите количество строк: ")) 
k2 = int(input("Введите количество столбцов: "))
B = np.array(range(q2, w2, 1))
for i in range(m2):
    print(B)


if m1 == k2:
  C = A*B
else:
  Z = "Упс! Что-то пошло не так..."

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

Введите количество чисел в массиве 1: 6
Введите количество строк: 2
Введите количество столбцов: 3
Введите первое число вектора в массиве 2: 11
Введите последнее число вектора: 14
Введите количество строк: 3
Введите количество столбцов: 1
[11 12 13]
[11 12 13]
[11 12 13]


0.24518236099993374

1.14. Поменяйте знак всех чисел из интервала (3; 9), хранящихся в векторе Z.

In [41]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 9)] *= -1
print(Z)
import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


0.4978923560001931

1.15.Подсчитать произведение ненулевых элементов на диагонали прямоугольной
матрицы. Для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [47]:
X = np.array([[1, 0, 1], 
              [2, 0, 2], 
              [3, 0, 3], 
              [4, 4, 4]]
             )
Z = np.prod(np.diag(X)[np.diag(X)!=0])
print(Z)

import timeit
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

3


0.5027270200002931